appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L8hAv/BJyWZ4u9ofQNUlvdCyGGuW6fVkI6YpgI7ark7DvcWm0Fl/1zkbODUIpZbtgdwkULTTFS8TH/2UA2FTO1Xy3gITc1ywvZBnYK8fWNbtHEzBbPnrKVlvT0zhTbgXs5BW85pGx36rmhG/qAsLpEn3697QjC4PcFgbLGf4leq34/fNcODAdjg+qCntfEwMnYH/wnlSf7bPwnQXV5u0yxXui+Ou+8IbQ6yVhc8sDuSYHHqtDwiiRuNcyt7Kg08RglACGG34Nwsufyy5L5F/era7Q4Qwnilvr4JiDhIXQ7dacLxair1vPetgLYA8vIswJve0YBN/G8JvQO81LutW5CfQlMUwBWx3iA3WpldgQuNyS9ymIx+8dmRuGafvUKeimC7fDL0YyzdvR9YFqDrRgtT2FREnw6GvjVd7hTiANx225iK3ILd/SpsWznP0TKLA6ADowGmq5Q5QZY+jUEDAXA6c5SFQQQl/MOSl7iAe7ZBkePhzNBceL+j+THX2xsHUpeSO+AubaWvh8W+IAJy2OAhRQscnERq5ZYi77xlE1XAjucyxeJsuw4nqNP9oMktNYrN+n4p55cG4BRlJwvjZMFwE8qN33WrX2ty0eonXd4PhyYA2sVX9dP4DNvbrvaI9FMKZCIw52AiiN/Bi2i7PEvn0LUzjU83W1Ln+IDCQt0s=}
